export const SEARCH_COLLAPSED_HEIGHT_PX = 80;
export const LOCATION_DETAILS_COLLAPSED_HEIGHT_PX = 180;
export const SNAP_POINTS_DEFAULT = [0, 1];
export const SNAP_POINTS_SEARCH = [0, SEARCH_COLLAPSED_HEIGHT_PX, 1];
export const SNAP_POINTS_LOCATION_DETAILS = [0, LOCATION_DETAILS_COLLAPSED_HEIGHT_PX, 0.5, 1];
export const SNAP_POINTS_LOCATIONS_LIST = [0, 200, 1];
